<a href="https://colab.research.google.com/github/urvihp1001/SudokuSolver/blob/main/SudokuSolver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as num

In [ ]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]
#example
print(num.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 0 1 9 0 0 5]
 [0 0 0 0 0 0 0 0 0]]


In [ ]:
def possible(row,column, number):
  global grid
  #is number in given row?
  for i in range(0,9):
    if grid[row][i] == number:
      return False#false means that ok the number exists here in row so cant be placed here
    #example: checking for 4 in row=1 and number=4
    #grid[1][0]==4- true
    #grid[1][1]==4-true....
    #true meaning where we can place
  #is number in given column
  for i in range(0,9):
    if grid[i][column] == number:
      return False
      #if we say 8 in col2
      #[0][2]=true
      #[1][2]=true
      #[2][2]=false
  #is number in given square
  x0=(column//3)*3
  y0=(row//3)*3
  for i in range(0,3):
    for j in range(0,3): #3X3 box
      if grid[y0+i][x0+j] == number:   #moves fwd within box
        return False #if number is within those 9 possible locns
  return True
  #backtracking means if python finds that input of a number is wrong- it goes 1 step back
  #and tries another number after scanning row and column
def solve():
  global grid
  for row in range(0,9):
    for column in range(0,9):
      if grid[row][column] == 0:
        for number in range(1,10):
          if possible(row,column,number):
            grid[row][column] = number #if it fits
            solve()#continue to next field
            grid[row][column] = 0 #if it gets stuck set prev field to 0 and resolve
            #keep setting prev field to 0 and resolve if we get stuck at a point
        return
  print(num.matrix(grid))
  input('More?') #output all possible solutions
solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More?
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More?
